object Day02 {
    // Points you earn for your move
    private val movePointMap = mapOf(
        "X" to 1,
        "Y" to 2,
        "Z" to 3,
    )

    enum class GameResult {
        WIN,
        LOSE,
        DRAW,
    }

    private val moveWinLoseDrawMap = mapOf<String, GameResult>(
        "Y" to GameResult.DRAW,
        "X" to GameResult.LOSE,
        "Z" to GameResult.WIN,
    )

    private val resultToScoreMap = mapOf<GameResult, Int>(
        GameResult.WIN to 6,
        GameResult.LOSE to 0,
        GameResult.DRAW to 3,
    )

    private val scoreTree = mapOf(
        // Opponent -> You -> score
        "A" to mapOf(
            "X" to 3, // rock (them) vs. rock (you)
            "Y" to 6, // rock (them) vs. paper (you)
            "Z" to 0, // rock (them) vs. scissors (you)
        ),
        "B" to mapOf(
            "X" to 0, // paper (them) vs. rock (you)
            "Y" to 3, // paper (them) vs. paper (you)
            "Z" to 6, // paper (them) vs. scissors (you)
        ),
        "C" to mapOf(
            "X" to 6, // scissors (them) vs. rock (you)
            "Y" to 0, // scissors (them) vs. paper (you)
            "Z" to 3, // scissors (them) vs. scissors (you)
        ),
    )

    fun rockPaperScissorsCheatSheet(): Int {
        val input = """
            B Z
            B Z
            B Y
            C Y
            B Y
            C Y
            C Y
            A Z
            B Y
            A Y
            C X
            A Y
            A Y
            C Y
            A Y
            B Y
            B Y
            C Y
            A Y
            A Y
            A Y
            C Y
            A Y
            B Y
            A Y
            B Y
            C Y
            B X
            A X
            A Y
            C X
            B Y
            C Y
            B Y
            B X
            C X
            B Y
            B Y
            A Y
            A X
            A X
            A Y
            B Y
            C Y
            C X
            A X
            B Y
            C Z
            B Y
            C X
            A Y
            A X
            C X
            A Y
            A Y
            A Y
            A Y
            B X
            C Y
            C Z
            B Y
            C Y
            A Y
            A Y
            B Y
            A Y
            C X
            B Y
            C Y
            C Y
            A Y
            C X
            B Y
            A Y
            B Y
            C Y
            C Y
            A Y
            B Y
            C Y
            C Y
            C Y
            A X
            A X
            B Y
            B Y
            C Z
            C Y
            B Y
            B Y
            B Y
            C Y
            A Y
            C Y
            A Y
            A Y
            A X
            C Y
            A X
            A Y
            A Y
            B Y
            B Y
            C Y
            C Y
            A Y
            A Y
            A X
            B Z
            C Y
            A Y
            A X
            C Y
            B Y
            C Y
            A Y
            A X
            A X
            A X
            A Y
            A X
            B Y
            A Y
            C Y
            A X
            B Y
            C Y
            B Y
            A X
            B Y
            B Y
            C Z
            C Y
            C X
            A Y
            C X
            B Y
            B Y
            C Y
            A X
            A X
            C Z
            B Z
            C Y
            C Y
            A X
            A X
            B Y
            B Z
            C Y
            B Y
            B Y
            B Y
            A X
            A X
            B Y
            C Y
            A Y
            C Y
            C Y
            A X
            B Y
            A Y
            A X
            C Y
            C X
            A Y
            A Y
            C Y
            C X
            C Y
            B Y
            A Y
            A Y
            C Y
            B Y
            C X
            A Y
            C X
            A X
            B Y
            C X
            A Y
            A Y
            A Y
            C Y
            C Y
            A Y
            A X
            C Y
            C Z
            B X
            C Z
            B Z
            A Z
            A Y
            B Y
            A Y
            B Y
            B Y
            A Y
            A Y
            C X
            C Y
            A Y
            A Y
            B Y
            A Y
            B Y
            B Z
            A Y
            B Y
            C Y
            A Y
            C Y
            B X
            A Y
            A X
            A Y
            A X
            A Y
            C Y
            A X
            C Y
            C Y
            A X
            B Y
            A Y
            B Y
            A Y
            A Z
            C Y
            B Z
            C X
            C Y
            C X
            B Y
            C X
            B Y
            A Y
            C Y
            A Y
            A X
            C Y
            A X
            A X
            C X
            C X
            C Y
            C X
            C Y
            A X
            B Z
            A Y
            B X
            B Y
            C Z
            B Y
            B Y
            B Y
            C X
            B Y
            A Y
            B Y
            A Y
            C Y
            C Y
            B Z
            B Y
            A X
            A Y
            C Y
            B Y
            C Y
            B Y
            B Y
            A X
            B Y
            B Z
            C Y
            A Y
            A Y
            A Y
            A Y
            A Y
            A Y
            C X
            B Y
            B Y
            C Y
            B Y
            B Y
            A Z
            C Y
            A Y
            A Y
            C Y
            C X
            A Y
            B Y
            A Y
            C X
            B Y
            A Y
            C Y
            B Y
            B Z
            A Y
            B Y
            A Y
            C Y
            A Y
            B Y
            C Y
            B Y
            A X
            C Z
            C Y
            A Y
            C Y
            B Y
            C Z
            A Y
            A Y
            C Y
            C X
            B Y
            C Y
            C X
            B Y
            C X
            A Y
            C X
            C Y
            B Y
            B Y
            A Y
            B Y
            A X
            C X
            C Y
            B Y
            A Y
            A X
            C Y
            C Y
            C Y
            C X
            B Z
            B Y
            C Y
            A X
            C Y
            A X
            C Y
            B Y
            B Y
            B Y
            B Y
            C X
            C Y
            C Y
            A Z
            B Y
            B Y
            A Y
            A Y
            B X
            A Y
            B Y
            B Y
            B Z
            C Y
            A X
            A X
            A Y
            B Z
            B Y
            C Y
            B Y
            B Y
            B Y
            B Y
            A X
            B Y
            C Y
            A Y
            B Y
            A X
            C Y
            C Y
            B Y
            B Y
            C Y
            B Y
            A Y
            A Y
            A X
            A Y
            B X
            B Y
            C Y
            C Y
            A Y
            A Y
            B Y
            B Y
            A X
            B Y
            A X
            C Y
            C Y
            C Y
            B Y
            A Y
            B Y
            A Y
            A Y
            A X
            C Y
            A Y
            A Y
            B Z
            C Y
            A X
            C X
            B Y
            C X
            C Y
            C X
            C X
            C Z
            A Y
            A X
            A Y
            B Z
            B Y
            A X
            A Y
            A X
            B Y
            A Y
            C X
            B Y
            B Y
            A Y
            A Y
            C Y
            A Y
            A Z
            C Y
            C Y
            C Z
            A Y
            C Y
            C Y
            C Y
            C Y
            A Y
            B Y
            B Y
            C Y
            A Y
            C Y
            C Y
            A X
            B X
            B Y
            A Y
            B Y
            A Y
            C Y
            A Y
            C Y
            B Y
            B Y
            B Y
            A Y
            C Y
            C X
            C X
            C X
            C X
            C Y
            C Y
            C X
            B Y
            A Y
            A X
            B Y
            C X
            B X
            C Y
            B Y
            C Y
            C X
            C Y
            B Y
            A Y
            A Y
            A Y
            C Y
            C Y
            A X
            A X
            C X
            A Y
            A Y
            B Y
            B X
            B Z
            C Z
            B Y
            B Y
            B Y
            B Y
            B Y
            A Y
            A Y
            B Y
            A Y
            C Z
            A Y
            C X
            A Y
            A Y
            C Y
            C X
            B Y
            A Y
            B Y
            B Y
            C Z
            A Y
            A Y
            A X
            C Y
            C Z
            B Y
            A X
            C Y
            C X
            B Y
            C Z
            A X
            A X
            A Y
            C Y
            A Z
            B Y
            B Y
            B Y
            B Y
            C Y
            B Y
            C X
            A Y
            C Y
            B Y
            B Y
            A Y
            A X
            A Y
            C Y
            C Y
            A X
            C Y
            B Y
            B Y
            C Y
            C Y
            A Y
            B Y
            A Y
            B Y
            A Y
            B Y
            C X
            A X
            C X
            B Y
            B Y
            B Y
            C Y
            B Y
            C Y
            B X
            A Y
            A Y
            C Y
            C X
            C X
            C Y
            C X
            A X
            A Y
            A Z
            A Y
            A Y
            B Y
            B Y
            C X
            C Y
            A Y
            B Z
            A Y
            A X
            A Y
            C Y
            A Y
            A X
            C Y
            B Y
            B Y
            C X
            A X
            A Z
            C Y
            B Y
            A X
            A Y
            C Y
            C Y
            A X
            C Y
            B Y
            A Y
            A X
            C Y
            B Y
            A Y
            A Y
            C X
            B Y
            B Y
            B Y
            C Z
            C Y
            C X
            C X
            B Y
            A X
            A Y
            B X
            A Y
            C Y
            B Y
            B Y
            B Y
            C Y
            C Z
            A Y
            C X
            C Y
            A Y
            A Y
            B Y
            B X
            B X
            B Y
            A Y
            A Y
            A Y
            C Y
            C Z
            B X
            C Y
            A Z
            A X
            B Y
            C Y
            B Y
            B X
            A Y
            A Y
            C Y
            B Y
            A X
            C X
            B Y
            C Y
            B Y
            B Y
            A X
            A Y
            A X
            C Y
            A Y
            C Y
            B Y
            A Y
            C Y
            A X
            A Y
            C Y
            C X
            C Y
            A X
            B Y
            B Y
            B Z
            A Y
            C Y
            B Y
            B Y
            C Y
            A X
            C X
            C Y
            C Y
            B Y
            C Y
            B Y
            A Y
            B Y
            A Y
            B Y
            A Y
            C Y
            B Y
            C X
            B Y
            C X
            A Y
            C Y
            A X
            C X
            B Y
            A Y
            B Y
            C X
            B Y
            C Y
            C Z
            A Y
            C Z
            C X
            C X
            A Y
            A X
            A Y
            B Z
            C Y
            C Y
            B Y
            A X
            A Y
            B Y
            C Y
            A Y
            A X
            B Y
            C Y
            A Z
            C Y
            B Y
            B Y
            B Y
            C Y
            A Y
            B Y
            A Y
            C X
            A X
            A Y
            B Y
            C Y
            B X
            C Y
            A X
            A Y
            A Y
            C Y
            A Y
            C Y
            A Y
            A X
            B Y
            C Y
            B Y
            C Y
            B Y
            B Y
            A Y
            A X
            A Y
            C Y
            A X
            C Y
            B Y
            B X
            C Y
            B Z
            C Y
            B X
            B Y
            C X
            C Y
            A X
            C Y
            C Y
            A X
            C Z
            C X
            B Y
            A X
            A X
            C Y
            B Y
            A Y
            A Y
            B Y
            B Y
            A X
            C Y
            B Y
            A X
            A Y
            B Y
            C Y
            A X
            A X
            A Y
            A X
            A X
            A Y
            A Y
            A Y
            A X
            C Y
            A X
            A Y
            A Y
            A Y
            B Y
            C Y
            C Y
            B Y
            A Y
            B Y
            B Z
            B Y
            B Y
            C Y
            B Y
            C X
            A Y
            C Y
            A Y
            C Y
            B Y
            C X
            B Y
            B Y
            C Z
            C Y
            B Z
            B X
            B Y
            A Z
            A Y
            B Y
            A Y
            C Y
            A X
            B Y
            C Y
            A Z
            A Y
            C Y
            C Y
            B Y
            C Y
            C X
            B Y
            C Y
            C X
            B X
            C X
            A X
            A X
            A Y
            C Y
            B Y
            C X
            B X
            A X
            B Y
            C Y
            A Y
            C X
            C Y
            B Y
            C Y
            B Y
            A Y
            B Y
            A Y
            A Y
            A Y
            A Y
            B X
            C X
            A Y
            B Y
            A X
            B Y
            C Y
            B Y
            A X
            A Y
            C Y
            A X
            C Z
            C Y
            A X
            B Y
            A Y
            B X
            A Y
            A Y
            A Y
            A Y
            A Y
            B Y
            B X
            A Y
            B Y
            C X
            C Y
            B Y
            B Y
            B Y
            B Y
            B X
            A Y
            A X
            B Y
            A X
            A X
            A Y
            B Y
            A Y
            A Y
            C Y
            B X
            B Y
            B Y
            A Y
            A X
            C Y
            A Y
            C Y
            A X
            B Y
            B Y
            A X
            A X
            A X
            A Y
            A X
            C Y
            C Z
            B Y
            B Y
            A X
            C Y
            B X
            A Y
            B Y
            A Y
            B Z
            B Y
            B Y
            A Z
            B Y
            A Y
            B Y
            B Y
            C X
            B Y
            A X
            B Y
            B Y
            C Y
            B Y
            A X
            C Y
            C Y
            C X
            C Y
            B Y
            B Z
            A Y
            B Y
            C X
            A Y
            B Y
            B Y
            A X
            B Y
            A Z
            B Y
            A Y
            C X
            B Y
            A Y
            B X
            A X
            C X
            C Y
            B Y
            A X
            B Y
            B Y
            C Y
            B Y
            C Y
            A Y
            C X
            C Y
            A Y
            C Y
            A Y
            C Z
            A Y
            B Y
            A Y
            C Z
            A Y
            C Y
            A Y
            C X
            C Y
            C Y
            A Y
            B Y
            B Y
            B Y
            A Y
            A Y
            B Y
            B Y
            B Y
            B Y
            B Y
            C Z
            A X
            A Y
            B Y
            B Y
            A Y
            B Y
            B Z
            B X
            A Y
            A Y
            A Y
            C X
            B Y
            A Y
            C Y
            A Y
            A Z
            B Y
            B Y
            A X
            B Y
            B Y
            A Y
            C X
            A X
            A Y
            A Y
            C Y
            B X
            A Y
            C Y
            C X
            A Z
            B Y
            B Y
            A X
            A Y
            C X
            B Y
            C Y
            A Y
            C Y
            B Y
            A Y
            A Y
            B Y
            B Y
            B X
            C Y
            A X
            A Y
            C X
            A Y
            C Y
            A Y
            C X
            C Y
            B Y
            A Y
            A Y
            A Y
            B Y
            A Y
            A X
            B Y
            B Y
            B Y
            A Y
            B Y
            B Y
            B Y
            C X
            B Y
            A Y
            C X
            B Y
            B Y
            A Y
            C Y
            B Y
            A Y
            B Y
            C Y
            B Y
            B Y
            C Y
            C X
            C X
            C Y
            B Y
            B Y
            A Y
            A Y
            A Z
            B Y
            C X
            B Y
            B Y
            C Y
            C Y
            C Y
            A Y
            A X
            A Y
            A Y
            C X
            C X
            B Y
            C Z
            C X
            A Z
            B Y
            A Y
            B Y
            C X
            A Y
            B Z
            C Y
            A Y
            B Y
            C Y
            C Y
            C Y
            A Y
            B Y
            C Y
            A X
            B Y
            A Y
            C Y
            A Y
            C X
            B Z
            B X
            C Y
            C Y
            C Y
            B Y
            C X
            A Y
            A Y
            B Y
            C Y
            A Y
            A Y
            B Y
            B Y
            A X
            A Y
            A Y
            B Z
            A X
            A X
            C Y
            C Y
            C X
            B X
            A Z
            B Y
            A X
            A Y
            B Y
            A Y
            B X
            A Y
            A Z
            B Y
            A X
            B Y
            A Y
            A X
            A Y
            A Y
            B Y
            A Y
            A X
            A Y
            C Y
            B Y
            B Y
            A Y
            A Y
            A X
            C Y
            A Y
            B Z
            C Y
            B Y
            A Y
            C Z
            A Y
            B Y
            A Y
            C Y
            B Z
            B Y
            B Y
            C Y
            B Y
            C Y
            C Z
            B Y
            B Y
            A X
            B Y
            C Y
            A Y
            B Y
            A X
            B Y
            C Y
            C Y
            A Y
            C X
            C X
            B Y
            C Y
            B Y
            A Y
            A X
            B Z
            B Y
            C Y
            A Y
            C X
            B Y
            C Z
            B Y
            A Y
            B Y
            A X
            A X
            A Y
            B Y
            A Y
            A X
            C Y
            C Y
            C X
            A X
            A X
            A Z
            C Y
            A Y
            A X
            A Y
            A Y
            B Y
            B Y
            C X
            B Y
            C Y
            A Y
            A Y
            A Y
            A X
            C X
            A Y
            C X
            A Y
            B Y
            A Y
            B Y
            A X
            C Y
            A X
            B Y
            A X
            B X
            A X
            B X
            C Y
            B X
            B Y
            B Y
            A X
            A Z
            C Z
            B Y
            C X
            A Y
            C Y
            A Y
            B Y
            C X
            B Y
            C Y
            C Y
            B Y
            A X
            B X
            C Z
            C X
            A X
            C Y
            B Y
            A X
            C Y
            C Y
            A Y
            B Y
            C Y
            C Y
            B Y
            B Z
            A Y
            A X
            C X
            B Y
            B Y
            C X
            A Y
            A Y
            B Y
            A X
            B Y
            B Y
            C X
            A Y
            B Y
            B Z
            C Y
            A X
            B Y
            A Y
            A Y
            B Y
            C Y
            A Y
            A Y
            A Y
            B Y
            A Y
            B Y
            B Y
            B X
            A Z
            B Z
            A Z
            A Y
            B Y
            C Y
            B Y
            B Y
            B Y
            B Y
            A Y
            A Y
            B Y
            B Y
            A Y
            C Y
            A Y
            C X
            A Y
            C X
            B Y
            B X
            C Y
            C X
            B Y
            B Y
            B Y
            B Y
            C Y
            A Z
            A Y
            B Z
            C Y
            A Y
            A Y
            B Y
            C X
            A X
            A Y
            C Y
            A Y
            C Y
            A X
            A X
            C Y
            B Z
            A X
            A Y
            B Y
            B Y
            A Y
            A Y
            A Y
            B Y
            B X
            A Y
            C X
            B Y
            C X
            C Y
            C Z
            C Y
            A X
            C Y
            A Y
            C Y
            C X
            A Y
            A Z
            A X
            A X
            A X
            B Y
            A Y
            C Y
            C Y
            C X
            A Y
            B Y
            A Y
            A X
            C X
            A Y
            B Y
            A Y
            C Y
            C Y
            C Y
            C Y
            C X
            B Y
            C X
            B X
            A X
            C Y
            B X
            C Z
            B Z
            B Y
            A Y
            B Y
            B X
            C X
            C X
            B Y
            C Y
            C Y
            A X
            A X
            C Y
            A X
            A Y
            A Y
            A Y
            C Y
            A Z
            C X
            C X
            B Y
            B Y
            A Z
            B Y
            A Y
            A Y
            A Y
            C Y
            B Y
            C Y
            B Y
            B Y
            A Y
            B Y
            A Y
            B Y
            C Y
            C X
            A Y
            A Y
            C Y
            A X
            C Y
            B Y
            A Y
            C X
            C X
            B Y
            A Y
            A Y
            C Y
            C Z
            A X
            C Z
            B Y
            B Y
            B Y
            C X
            A Y
            B Y
            C Y
            B Y
            C Y
            B Y
            B Y
            A Y
            B Y
            A Z
            A Y
            A X
            A Y
            A X
            A Y
            A X
            A Y
            A Y
            C Y
            A Y
            A Y
            B Z
            A Y
            A Y
            C Y
            B X
            C Y
            A Y
            C X
            C Y
            A Y
            C Y
            B Y
            A X
            A Y
            A X
            A Y
            B Y
            C X
            C Y
            C X
            C X
            A Y
            C Y
            A Y
            B Y
            C X
            C X
            A Y
            C Y
            B X
            C X
            B Y
            C X
            A Y
            C Y
            A X
            B X
            C Y
            C Y
            C Y
            B Y
            A Y
            A X
            A Y
            A Y
            B Y
            B Y
            A Y
            C Y
            C Y
            B Y
            B Y
            B Y
            B Y
            B Y
            B Z
            A Y
            A X
            C Y
            B Y
            C Y
            C X
            B Y
            A Y
            B Y
            C Y
            B Z
            A X
            B X
            B Y
            A X
            B Z
            A X
            A X
            B Y
            B X
            C X
            A Y
            A Y
            B Y
            B Z
            A Y
            B X
            C Y
            C Y
            B Y
            A Y
            A Y
            B Y
            A Y
            B Z
            C Y
            B Y
            A X
            C X
            A Y
            B Y
            B Y
            A Y
            C X
            C Y
            C Z
            B Y
            B Y
            A Y
            C Y
            A X
            C X
            A X
            C X
            C Y
            B Y
            A Z
            A Y
            A X
            C Y
            A X
            C X
            A Y
            B Y
            C Z
            B Y
            C Z
            B Y
            B Y
            A Y
            A Z
            B Z
            A Y
            A Y
            B Y
            A Y
            A Z
            B Y
            B Z
            B Y
            B Z
            B Y
            A Y
            A Y
            B Y
            B Z
            B Y
            A Y
            B Y
            C X
            B Y
            C X
            A Y
            B Y
            C Y
            A Y
            A Y
            B Y
            B Z
            A Y
            A Y
            B Y
            C X
            C Y
            C Y
            A Y
            B Y
            A Y
            A X
            B Z
            A Y
            A X
            A X
            A Z
            A Z
            A Y
            C Y
            A Z
            A Y
            C Y
            A Y
            B Z
            C X
            C Y
            C Y
            B Y
            C X
            C X
            A Y
            C Y
            B X
            C Y
            B Y
            B Y
            B Y
            B X
            C Y
            C Y
            A X
            A Y
            B Z
            A Y
            B Y
            A Y
            B Y
            B Y
            A Y
            B Y
            B Z
            A X
            C Y
            A Y
            A X
            A Y
            B Y
            A Y
            B Y
            B Y
            C Y
            B Y
            B Y
            C Y
            B Y
            C X
            C Y
            A X
            B X
            C Y
            B Y
            C X
            A Y
            A Y
            B Y
            A Y
            B Y
            A Y
            B Z
            C Y
            B Y
            B Y
            C Y
            A Y
            A X
            B X
            A Y
            B Y
            B Y
            C Y
            A Y
            C Y
            A Y
            A Y
            B X
            C X
            A Y
            B Y
            B Y
            B Y
            B Y
            A Y
            C Y
            A X
            B Y
            A Y
            C Y
            A X
            A Y
            A Y
            C Y
            A Y
            B Y
            A X
            A Y
            B Y
            A X
            C X
            C Y
            A Y
            A Y
            B Y
            C Y
            C Y
            A X
            C Y
            C Y
            B Y
            A Y
            C X
            B Y
            A Y
            A Y
            A Y
            A Y
            B Y
            A Y
            B Z
            A Y
            B Z
            A X
            A Y
            A Y
            A X
            C Y
            A X
            A X
            C Y
            A X
            A X
            A Y
            C Y
            A Y
            B Y
            A X
            C Z
            A Y
            B X
            A Y
            B Y
            C Y
            A Y
            B Y
            A Y
            C Y
            B X
            C Y
            B Y
            A Y
            B Y
            C Y
            C Y
            A Y
            A Y
            C X
            A X
            A Y
            B Y
            C Y
            C Y
            B Z
            C Y
            C Y
            B Y
            B Z
            A Y
            A Y
            B Y
            B Y
            B Y
            A X
            B Y
            C Y
            B Y
            A Y
            C Y
            C Y
            C X
            B Y
            A Y
            B Y
            C Y
            B Y
            C Y
            A Y
            A Y
            C Z
            C X
            B Y
            A Y
            A X
            B Y
            C Y
            A Y
            C Y
            B Y
            C Y
            C X
            A X
            C Y
            A Y
            A X
            A X
            A X
            C Y
            C Y
            A X
            C Y
            C Y
            C Z
            A X
            C Y
            C X
            B Z
            C Y
            A Y
            A X
            C X
            A Y
            C Z
            A Y
            C X
            B Y
            A Y
            C X
            A X
            B Y
            B Y
            A X
            C Y
            B Y
            C X
            C X
            B Y
            A Y
            C X
            C Z
            C X
            C X
            A Y
            C Y
            C Y
            C Y
            A X
            B Y
            C Y
            A X
            C X
            C Y
            B X
            B Y
            C Y
            A Y
            A Y
            B Y
            B Y
            B Y
            B Y
            B Y
            B Y
            A Y
            A X
            B Y
            B Y
            B Y
            B Z
            B X
            C Y
            A X
            A Y
            A Y
            C Y
            A Y
            A X
            C X
            A Y
            A Y
            C X
            A Y
            B Y
            A Y
            B Y
            C Y
            C X
            A X
            C Y
            C Y
            B Z
            A Y
            C Z
            A X
            A X
            B Y
            A X
            A Y
            B Y
            C Y
            B Y
            C Y
            A Y
            A X
            C Y
            C Y
            C Y
            A X
            C Y
            A Y
            A Z
            A X
            C Z
            C Y
            C X
            B Y
            C Y
            B Y
            C Y
            A Y
            C X
            B Y
            C Y
            C X
            A Y
            B Y
            C X
            C Y
            C Y
            A Y
            A Y
            B Y
            A X
            B Y
            A Y
            C Y
            B X
            C Y
            B Y
            B Y
            B Y
            B Y
            A X
            C Y
            A X
            A Y
            A Y
            B Z
            C X
            B Y
            B Y
            A X
            C Y
            A Y
            A Y
            B Y
            A X
            B Z
            B Y
            B Y
            A Y
            A X
            A X
            A Y
            A Y
            C X
            C X
            A X
            B Y
            C X
            C Z
            C Y
            B Y
            C Z
            A Y
            A Y
            B Y
            B Y
            C X
            A Z
            A X
            A Y
            B Y
            B Y
            A Y
            A X
            A X
            A Y
            A Y
            C Y
            B Y
            B Y
            A X
            A X
            C Y
            C X
            C Z
            A Y
            A Y
            A Y
            C Y
            C X
            B Y
            C Y
            A X
            B Y
            C Y
            A Y
            A X
            B Y
            C Y
            A Y
            B Y
            C X
            A Y
            A Y
            B Y
            B Y
            C Y
            A Y
            A Y
            A X
            B Z
            A X
            A Y
            C Y
            C Y
            A Y
            A Y
            C Y
            C Y
            B Y
            A Y
            A X
            A Y
            C X
            C X
            B Y
            B Y
            A Y
            A X
            C X
            A Y
            B Y
            B Y
            A Y
            C Y
            B Y
            C X
            C Y
            A Y
            A Y
            C Y
            B Y
            B X
            C Y
            C Y
            B Y
            B X
            A Y
            B X
            A X
            B Y
            C X
            A X
            B Y
            A Y
            A Y
            A Y
            C Y
            B X
            A Y
            B Y
            A Y
            A X
            C Z
            B Y
            A Y
            B Y
            B Y
            A Y
            A Y
            B Y
            C Y
            A Y
            C Y
            B Y
            C Y
            A X
            A Y
            C Y
            A Y
            C Y
            B Y
            B Y
            C Y
            A Y
            A Y
            B Y
            A Y
            C Y
            A Y
            A Y
            B Y
            B Y
            B Y
            B Y
            A X
            A X
            C Y
            C Y
            B X
            C Z
            C Y
            A X
            A Y
            B Y
            A Y
            C Y
            C X
            B Y
            B Z
            C Y
            A X
            A Y
            A X
            B Y
            B X
            B Y
            B X
            C Y
            A Z
            B Y
            C Y
            A Y
            A X
            C Y
            C X
            B Y
            A Y
            A Y
            A X
            C X
            A Y
            C X
            A Y
            C Y
            C X
            A X
            C Z
            B Y
            A X
            B Y
            A Y
            A X
            A X
            A Y
            A Y
            A Y
            C X
            C X
            A Y
            A Y
            B Y
            C Y
            C Y
            B Y
            C Y
            A Y
            C Y
            A Y
            B Y
            B Y
            A Y
            B Y
            C X
            B X
            A X
            A X
            B Y
            B Y
            B Y
            C Z
            C Y
            B X
            A X
            B Y
            A X
            B Y
            A Y
            B Y
            C Y
            A Y
            A Y
            C Y
            B Y
            A Y
            A Y
            C Y
            C Y
            C Y
            B Y
            A Y
            C Y
            C Y
            B X
            B Y
            B Y
            A Y
            B X
            A Y
            B Y
            C Z
            B Z
            B Y
            C Y
            B Z
            C Y
            C Y
            B Z
            A Y
            A Y
            A Y
            C Z
            B Y
            A Y
            A Y
            C Z
            A Y
            A Y
            A Y
            B Y
            C X
            A Y
            A Y
            A Y
            A Y
            A Z
            C Y
            A X
            A Y
            A Y
            A Y
            B Y
            B Y
            A X
            B Y
            A Y
            A Z
            A Y
            A Y
            A Y
            A Y
            A Y
            C Y
            B Y
            C X
            B Y
            C Y
            C X
            B Y
            A Y
            B Y
            A Y
            B Y
            B Y
            A Y
            A X
            A Y
            B Y
            B Y
            B Y
            A X
            C Y
            A Y
            B Y
            B X
            A Y
            C X
            B Y
            A X
            A Y
            A Y
            C Z
            C Y
            B Y
            C Y
            B Z
            A X
            B Y
            C Y
            B Y
            A Y
            A Y
            C Y
            A Y
            C Y
            A Y
            C Y
            A X
            A X
            A Y
            B Y
            B Y
            B X
            A X
            A Y
            A Y
            A X
            A Y
            C Y
            C Y
            B Y
            A X
            C Y
            A Y
            C X
            B Y
            A Y
            C Y
            C X
            A Y
            C Y
            B Y
            B Y
            A X
            A Y
            C Y
            A X
            A X
            B Y
            B Y
            A Y
            A X
            A Y
            B Y
            A X
            B Y
            A X
            A X
            C Z
            C Z
            B Y
            A X
            B Y
            A Y
            B Y
            B Z
            A Y
            A X
            C Y
            C Y
            C Z
            C Y
            C Z
            A X
            A Y
            C Y
            C Y
            C Y
            A Y
            B Y
            A Y
            A Y
            B Y
            C Y
            B Z
            A Y
            C Y
        """.trimIndent()

        val rounds = input.split("\n")
        val moves = rounds.map { it.split(" ") }

//        println(rounds)
//        println(moves)

        val answer = moves
            .map { move ->
                val them = move[0]
                val you = move[1]

                val score = evaluateScore(you, them)
//                println("Them = $them, you = $you, score = $score")

                score
            }
            .reduce { acc, curr -> acc + curr }

        return answer
    }

    fun rockPaperScissorsTargetResult(): Int {
        val input = """
            A Y
            B X
            C Z
        """.trimIndent()

        val rounds = input.split("\n")
        val moves = rounds.map { it.split(" ") }

//        println("moves = $moves")

        val answer = moves.map { move ->
            val desiredResultLetter = move[1]!!
            val desiredResult = moveWinLoseDrawMap[desiredResultLetter]!!

//            println("them = $them, desired result = $desiredResultLetter -> $desiredResult")

            1 + resultToScoreMap[desiredResult]!!
        }
        .reduce { acc, curr -> acc + curr }

        return answer
    }

    private fun evaluateScore(yours: String, theirs: String): Int {
        val baseScore: Int = movePointMap[yours]!!

        val attackScore = scoreTree[theirs]!![yours]!!

        return baseScore + attackScore
    }
}